version: '3.8'

services:
  api:
    build: ./back
    ports:
      - "8000:8000"
    env_file: 
      - "./back/.env"
    network_mode: host 
  front:
    build: ./front
    ports:
      - "5000:5000"
    network_mode: host 
    