version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: ./back
    ports:
      - "8000:8000"
    env_file: 
      - "./back/.env"
    network_mode: host
    depends_on:
      - db
    volumes:
      - api:/app/PersistDirectory 
  front:
    build: ./front
    ports:
      - "5000:5000"
    network_mode: host 
volumes:
  api:
  db_data: