version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: host  

  db_service:
    container_name: mysql_connector
    build: ./ddbb
    restart: always
    env_file: 
      - "./ddbb/.env"
    ports:
      - "8001:8001"
    network_mode: host    

  api:
    build: ./back
    ports:
      - "8000:8000"
    env_file: 
      - "./back/.env"
    network_mode: host
    depends_on:
      - db
    volumes:
      - api:/app/PersistDirectory 
  front:
    build: ./front
    ports:
      - "4200:4200"
    network_mode: host 
volumes:
  api:
  db_data: