version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    env_file: 
      - "./mysql/.env"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  db_service:
    container_name: mysql_connector
    build: ./ddbb
    restart: always
    env_file: 
      - "./ddbb/.env"
    ports:
      - "8001:8001"
#    network_mode: host    
    depends_on:
      - db
    links:
      - db  

  rag_documents:
    build: ./RAG_documents
    ports:
      - "8000:8000"
    env_file: 
      - "./RAG_documents/.env"
    network_mode: host

    volumes:
      - RAG_documents:/app/PersistDirectory
  rag_ddbb:
    build: ./RAG_ddbb
    ports:
      - "8002:8002"
    env_file: 
      - "./RAG_ddbb/.env"
    network_mode: host
    volumes:
      - rag_ddbb:/app/configs_folder   
  front:
    build: ./front
    ports:
      - "4200:4200"
    network_mode: host 
volumes:
  RAG_documents:
  db_data:
  rag_ddbb: