version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    env_file: 
      - "./mysql/.env"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  db_service:
    container_name: mysql_connector
    build: ./ddbb
    restart: always
    env_file: 
      - "./ddbb/.env"
    ports:
      - "8001:8001"
#    network_mode: host    
    depends_on:
      - db
    links:
      - db  

  api:
    build: ./back
    ports:
      - "8000:8000"
    env_file: 
      - "./back/.env"
 #   network_mode: host

    volumes:
      - api:/app/PersistDirectory 
  front:
    build: ./front
    ports:
      - "5000:5000"
    depends_on:
      - api
      - db_service
    # links:
    #   - api
    #   - db_service    
#    network_mode: host 
volumes:
  api:
  db_data: